# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fastT1FM', [dirname(__file__)])
        except ImportError:
            import _fastT1FM
            return _fastT1FM
        if fp is not None:
            try:
                _mod = imp.load_module('_fastT1FM', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fastT1FM = swig_import_helper()
    del swig_import_helper
else:
    import _fastT1FM
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def MakeDMatrix(*args):
  return _fastT1FM.MakeDMatrix(*args)
MakeDMatrix = _fastT1FM.MakeDMatrix

def GetDArray(*args):
  return _fastT1FM.GetDArray(*args)
GetDArray = _fastT1FM.GetDArray

def SetDArray(*args):
  return _fastT1FM.SetDArray(*args)
SetDArray = _fastT1FM.SetDArray

def GetDvector(*args):
  return _fastT1FM.GetDvector(*args)
GetDvector = _fastT1FM.GetDvector

def SetDvector(*args):
  return _fastT1FM.SetDvector(*args)
SetDvector = _fastT1FM.SetDvector

def MakeDvector(*args):
  return _fastT1FM.MakeDvector(*args)
MakeDvector = _fastT1FM.MakeDvector

def MakeIvector(*args):
  return _fastT1FM.MakeIvector(*args)
MakeIvector = _fastT1FM.MakeIvector

def GetIvector(*args):
  return _fastT1FM.GetIvector(*args)
GetIvector = _fastT1FM.GetIvector

def SetIvector(*args):
  return _fastT1FM.SetIvector(*args)
SetIvector = _fastT1FM.SetIvector

def Saupe2X(*args):
  return _fastT1FM.Saupe2X(*args)
Saupe2X = _fastT1FM.Saupe2X

def rfastT1FM_multi(*args):
  return _fastT1FM.rfastT1FM_multi(*args)
rfastT1FM_multi = _fastT1FM.rfastT1FM_multi
# This file is compatible with both classic and new-style classes.


